name: 'auth0_lock'
version: 0.1.0
description: A Dart wrapper for Auth0 Lock
author: Andres Araujo <a.araujo.azua@gmail.com>
homepage: https://github.com/andresaraujo/auth0_lock.dart

environment:
  sdk: '>=1.0.0 <2.0.0'

dev_dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'

transformers:
- dart_to_js_script_rewriter